/*

OPEADORES LÓGOCOS 

&& -> AND -> E  = TODAS AS EXPRESSÕES NECESSITAM SER VERDADEIRAS PARA RETORNAR TRUE 
|| -> OR -> OU  = SÓ SERÁ FALSE SE TODAS AS ALTERNATICAS FOREM FALSAS
! -> NOT -> NÃO  = 

*/

